### ISSUE TITLE
Salty Boy not updating

### ISSUE THREAD

**Issue by AaroPro** [FranciscoAT/saltyboy#26]
Currently the bot is not updating the stats and is not betting.  Seems like the server is responding with a 404;
GET https://sb.scorecardresearch.com/p?c1=2&c2=6745306&ns_type=hidden&ns_st_sv=5.1.3.160420&ns_st_smv=5.1&ns_st_it=r&ns_st_id=1649996827568&ns_st_ec=2&ns_st_sp=1&ns_st_sc=1&ns_st_sq=1&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=hb&ns_st_po=300919&ns_st_cl=0&ns_st_hc=10&ns_st_mp=js_api&ns_st_mv=5.1.3.160420&ns_st_pn=1&ns_st_tp=0&ns_st_ci=39284760856&ns_st_pt=300919&ns_st_dpt=300919&ns_st_ipt=60004&ns_st_et=300919&ns_st_det=300919&ns_st_upc=300919&ns_st_dupc=300919&ns_st_iupc=60004&ns_st_upa=300919&ns_st_dupa=300919&ns_st_iupa=60004&ns_st_lpc=300919&ns_st_dlpc=300919&ns_st_lpa=300919&ns_st_dlpa=300919&ns_st_pa=300919&ns_ts=1649997130179&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=0&ns_st_dbt=0&ns_st_bp=0&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=0&ns_st_dpc=0&ns_st_pp=0&ns_st_br=0&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=Salty%27s%20Dream%20Cast%20Casino!%20Place%20your%20bets%20at%20www.saltybet.com&ns_st_ct=vc&ns_st_ge=Gaming&ns_st_st=SaltyBet&ns_st_ce=1&ns_st_ia=0&ns_st_ddt=2022-04-15&ns_st_tdt=*null&ns_st_pu=*null&ns_st_ti=*null&c3=TWITCH&c4=twitch.tv&c6=*null&c7=https%3A%2F%2Fplayer.twitch.tv%2F%3Fchannel%3Dsaltybet%26parent%3Dwww.saltybet.com&c8=Twitch&c9=https%3A%2F%2Fwww.saltybet.com%2F&cs_ucfr=*null net::ERR_BLOCKED_BY_CLIENT
Image (async)
httpGet @ player-main-d50680d9a5c7813aa9f2.js:1
n @ player-main-d50680d9a5c7813aa9f2.js:1
newEvent @ player-main-d50680d9a5c7813aa9f2.js:1
n @ player-main-d50680d9a5c7813aa9f2.js:1
setTimeout (async)
(anonymous) @ player-main-d50680d9a5c7813aa9f2.js:1
t @ player-main-d50680d9a5c7813aa9f2.js:1
resume @ player-main-d50680d9a5c7813aa9f2.js:1
n @ player-main-d50680d9a5c7813aa9f2.js:1

<html>
<body>
<div aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(225, 0, 0) !important;">GET <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--color-text-primary); text-decoration: underline; cursor: pointer; word-break: break-all;">https://sb.scorecardresearch.com/p?c1=2&amp;c2=6745306&amp;ns_type=hidden&amp;ns_st_sv=<span class="devtools-link-ellipsis" style="box-sizing: border-box; min-width: 0px; min-height: 0px;">…</span>.saltybet.com&amp;c8=Twitch&amp;c9=https%3A%2F%2Fwww.saltybet.com%2F&amp;cs_ucfr=*null</span> net::ERR_BLOCKED_BY_CLIENT</span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(27, 27, 27); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | Image (async) |   |  
-- | -- | -- | --
  | httpGet | @ | player-main-d50680d….js:1
  | n | @ | player-main-d50680d….js:1
  | newEvent | @ | player-main-d50680d….js:1
  | n | @ | player-main-d50680d….js:1

</span></div>
</body>
</html>

**Comment by FranciscoAT** [comment]
Kicked the bot should be up again. That GET request looks really weird though. Where did you get this stack trace from?

**Comment by AaroPro** [comment]
Cool I see it working now. Honestly I might’ve pulled from the wrong bot because I mess with multiple. My mistake.

**Comment by AaroPro** [comment]
Bot is not responding/updating/betting again
