### ISSUE TITLE
Question and a betting mode request: Upsets

### ISSUE THREAD

**Issue by ReiMasa** [FranciscoAT/saltyboy#29]
Question:

Has it been considered to import old fighter data that has been posted on other bot githubs? Some of them have years worth of data, which is valuable because saltybet hasn't had an update in several as well.

Request:

Would it be possible to include a betting mode for upsets? Upsets can be a very easy way to get starting salt instead of piling into low odds.

Thanks!

**Comment by FranciscoAT** [comment]
Hey there I think it might entirely be possible to update the currently deployed database with a new one. Would require a bit of work on my part to get a script to safely update the existing data. Would happen to have links to where I could access a database dump of an past SaltyBet matches?

As for the request there's generally very little more I want to do with the project. There's a few minor UI updates I've been considering such as displaying statistics right in the view rather than requiring users to click on the extension button UI. However, when I'll have time to do this I'm not sure. I'm always accepting Merge Requests however! The `README.md` should be able to get you started and you can simply write out a new betting strategy. I'll be happy to review it!

**Comment by ReiMasa** [comment]
Here is some links to the ones I know of: 
https://github.com/saltbot-org/saltbot/tree/master/data
[new-record-data.txt](https://github.com/TSolo315/SaltyBetTrueSkill/blob/master/new-record-data.txt)
and record-data.txt 
There is possibly some more in different formats. I found them by searching "saltybet" in github and just going through repositories.

Oh, I see. I'm not the most savvy coder but my guess for an "upset mode" would just be to take the opposite option of the "best guess" and may be doable with just a line swap? I'll take a look at it

**Comment by FranciscoAT** [comment]
> Tried building the extension myself and inputting the new bet mode where I just swapped some lines in "naive" bet. Can see and select my bet mode, but the debug for the extension doesn't even connect to the login or anything to bet, even on other bet modes. No idea what to do here.

Can you clarify what you mean by "extension doesn't even connect to the login or anything to bet"? It's also possible you need to reload your extension. By doing so I recommend first going to `chrome://extensions` then hitting the "Reload" button on the unpackaged extension. I would also advise temporarily disabling the SaltyBet extension that was installed via the Chrome Web Store. Then refresh the SaltyBet web page. Additionally if maybe there are some exceptions being thrown by the newly changed code you should see a "ERROR" button under the unpackaged extension card for SaltyBoy. This might help you debug things.

Let me know if this helps.

**Comment by ReiMasa** [comment]
Yeah, it was the second bit that caught me. I didn't notice the chrome errors in the extensions until looking over it again a few ago. I've fixed it and it seems it's working correctly. [https://i.imgur.com/8CQ4SEZ.png](url)

Looks like my routine also worked just by swapping the colors in the "naive" bet and it is betting on the unfavorable winner. The hardest part was fixing the manifest so it could be compiled on windows since it can't use the unix functions for zip, and rm.

I'll watch over it and see if it's working properly and submit it, but since it's just literally a few line changes of your code, I'm not sure how you'd want it put it in :P

**Comment by FranciscoAT** [comment]
I would suggest taking a look into WSL2 fwiw.

**Comment by ReiMasa** [comment]
> WSL2

Ooh, I looked into that in a quick google search now and that would indeed by pretty handy. I'll install that, but I just removed the RM part, and changed it to 7zip to get it working easily.

**Comment by FranciscoAT** [comment]
> > WSL2
> 
> Ooh, I looked into that in a quick google search now and that would indeed by pretty handy. I'll install that, but I just removed the RM part, and changed it to 7zip to get it working easily.

If you do submit an MR feel free to update the `README.md` to include what you had to do to get it working on Windows.

**Comment by ReiMasa** [comment]
> > > WSL2
> > 
> > 
> > Ooh, I looked into that in a quick google search now and that would indeed by pretty handy. I'll install that, but I just removed the RM part, and changed it to 7zip to get it working easily.
> 
> If you do submit an MR feel free to update the `README.md` to include what you had to do to get it working on Windows.

I'm trying to figure out how to do a request, and I can't seem to do one? The button is greyed out. I don't know if it's something I'm missing on my end. Never done these before :P

**Comment by FranciscoAT** [comment]
Related PR: https://github.com/FranciscoAT/saltyboy/pull/31

**Comment by FranciscoAT** [comment]
Merged #31 closing.
