### ISSUE TITLE
SaltyBoy down?

### ISSUE THREAD

**Issue by ReiMasa** [FranciscoAT/saltyboy#32]
Match data is getting NULLs.

**Comment by ReiMasa** [comment]
Working again.

**Comment by ReiMasa** [comment]
Closed too early. Seems like it's getting hung on certain matches, or stuck on nulls.

**Comment by DeaconBluze** [comment]
I'm experiencing a similar issue. In all be exhibition matches I'm getting the message shown in the attachment. I've tried disabling the extension and reloading Salty Bet, but am getting the same results.

![SaltyBoy Error](https://user-images.githubusercontent.com/109566198/179650703-18a50317-26ae-4675-b1bf-d6b91e9c3fe8.png)

**Comment by FranciscoAT** [comment]
Gave the can a kick. Looks to be happy again.

https://tenor.com/bkVd3.gif

**Comment by DeaconBluze** [comment]
Sure does, thank you!

**Comment by ReiMasa** [comment]
Looks like it may be down again. API current-match stuck on a match for two fighters that fought two hours ago.
