### ISSUE TITLE
Bot stopped?

### ISSUE THREAD

**Issue by Warbizzle** [FranciscoAT/saltyboy#38]
Bot stopped betting. keeps saying "Current match from server is out of date." when i look at the error msgs

**Comment by FranciscoAT** [comment]
Yea it happens from time to time thanks for the heads up. Still not sure why things time out from time to time. I might introduce some lazy docker compose way of handling the exception

**Comment by FranciscoAT** [comment]
should be happy again.

**Comment by Synthawk** [comment]
It's still down.

**Comment by FranciscoAT** [comment]
It was up but died again late last night. Not sure why, this has been a re-occuring issue. I have some extra debug logs this time around, hopefully I cant track down the issue now.

**Comment by Synthawk** [comment]
Good luck, and yeah it's up and working again right now.

**Comment by Synthawk** [comment]
Looks like it went down again, hopefully you can get some good logs from this failure too.

Do you want me to open new issues when this occurs or just comment on this thread?

**Comment by FranciscoAT** [comment]
Feel free to make a new issue. I'll see if I can't tackle things later today. This is strange, typically it runs for a few weeks before exploding.
