### ISSUE TITLE
Saltyboy Scraper sometimes crashes irrecoverably (if server down read this!)

### ISSUE THREAD

**Issue by Synthawk** [FranciscoAT/saltyboy#39]
Making a new thread on this since the last one is closed. Saltboy appears to be down again.

I'm curious if it's something in the exhibition matches that is causing it to hang up and crash.

**Comment by FranciscoAT** [comment]
Out of access to my laptop right now. But no, I'm pretty convinced it's `socket.recv` or the `socket.send` call. Despite setting timeouts I think it's hanging there and never timing out. Either I set it wrong or there's something funky going on with the `SSLContext` wrapper.

**Comment by FranciscoAT** [comment]
Going to leave this issue open until I have a fix in for this. Sometimes it looks like the Python call to `socket.recv` will hang. Based off of some reading online it looks like `socket.settimeout` will not always do what I want. There appears to be others who say that infrequently, like Saltyboy, the `recv` call will hang despite have a timeout set. 

From those readings it looks like the general suggestion is to use Python's builtin `select` library to wait for information before calling `recv` and depending on the timeout to be called. This issue will be related to re-write the server to leverage the `select` library which in theory should hopefully reduce the crash rate.

**Important:** If extension is complaining about the server being out of date there's a 99% chance it's the scraper that failed for the above reason. Just add a comment on this existing issue if the server is dead and I'll give it a kick.

**Comment by Synthawk** [comment]
Server appears to have been down for a bit now. Through at least a full tournament and exhibitions.

**Comment by FranciscoAT** [comment]
Probably down will kick later today :)

**Comment by FranciscoAT** [comment]
> Server appears to have been down for a bit now. Through at least a full tournament and exhibitions.

bot is up :)

**Comment by AaroPro** [comment]
Bot crashed again a few matches prior to a tourney.

**Comment by FranciscoAT** [comment]
> Bot crashed again a few matches prior to a tourney.

On vacation at the moment. Will try and have things running in the next 24-48

**Comment by FranciscoAT** [comment]
> Bot crashed again a few matches prior to a tourney.

Sorry it still isn't up. Thought I might briefly have access to a computer but no. Returning from vacation tomorrow :)

**Comment by FranciscoAT** [comment]
Okay sorry for long downtime, back from vacation and bot is kicked and running.

**Comment by AaroPro** [comment]
No worries.  Noticed it wasn't working and this ongoing issue.  Noticed it stopped working after September 12, 2022 10:56pm EST again.  Maybe this will help narrow down the issue.  This was 89 matches into a matchmaking (12239) and it was a match between Mami EX vs Fernandeath.  Trying to give as much detail as possible.

**Comment by Titanoktonon** [comment]
will saltyboy ever come back? feelsbadman

**Comment by FranciscoAT** [comment]
> will saltyboy ever come back? feelsbadman

Whoop didn't know it died! So sorry, should be back now! Been a busy few months haven't had much time to dedicate to a better solution here. I might just write a crontab to restart the bot on a 24 hour basis or something as a rough "fix".

**Comment by Titanoktonon** [comment]
It returned, thanks.

**Comment by Titanoktonon** [comment]
Bot is down again.

**Comment by FranciscoAT** [comment]
> Bot is down again.

ack

**Comment by FranciscoAT** [comment]
Added a temporary hack to just auto-restart the scraper every 6 hours, hopefully this will close some gaps in downtime.

**Comment by AaroPro** [comment]
Seems to be down again.  Looks to have gone down about 3:32 PM EST.  Given the 6 hour restart, I guess let's see if it comes back at 9:32PM EST

**Comment by FranciscoAT** [comment]
Should be every 6 hours UTC. away from computer so should kick itself at
midnight UTC. will try and kick manually in a few hours when I'm home :)

**Comment by FranciscoAT** [comment]
Looks like the crontab wasn't working as wanted. Did a manual kick. Hopefully I will have some time over the break to finally resolve this issue :)

**Comment by Titanoktonon** [comment]
Bot is down.

**Comment by Titanoktonon** [comment]
Bot died

**Comment by Titanoktonon** [comment]
Any predictions on when the bot will come back?

**Comment by FranciscoAT** [comment]
Oh I'm sorry I thought I had already kicked this I'll be able to kick it
more likely within the next 24 hours when I get home!

**Comment by FranciscoAT** [comment]
> Any predictions on when the bot will come back?

hopefully should be up now :)

**Comment by Titanoktonon** [comment]
Bot is down.

**Comment by AaroPro** [comment]
It is down currently.  This is the last bet I have recorded (unsure of timezone);

(Matchmaking) Salty's Dream Cast Casino 12951 | Donald mcdonald vs Awakened kyle dunamis | 5147 on Awakened kyle dunamis | Donald mcdonald | -5147 | February 14, 2023 7:36pm

**Comment by FranciscoAT** [comment]
should be alive once again thanks for the heads up :)

one of these days I'll fix it's reliability lol

**Comment by Titanoktonon** [comment]
Welp... bot crashed

**Comment by FranciscoAT** [comment]
Will kick it shortly :) thanks for the heads up.

**Comment by Titanoktonon** [comment]
I think the bot broke. Stopped working in matchmaking and tournament, but it works in some exhibitions.

**Comment by DumpyCrumpet** [comment]
Yeah, bot seems to be nonfunctional.

**Comment by Titanoktonon** [comment]
Nothing yet.

**Comment by FranciscoAT** [comment]
Apologies been away from a computer this past week. Will reboot sometime
today.

**Comment by UnBayleefable** [comment]
i am once again asking for your help in restarting the service. i bet with all the time spent restarting it you could have had it fixed by now haha.

**Comment by FranciscoAT** [comment]
Kicked it. Wrote a patch to hopefully resolve the issue. Letting it run
overnight will try to deploy tomorrow.
