### ISSUE TITLE
bot issues 

### ISSUE THREAD

**Issue by SayYouLoveVi** [FranciscoAT/saltyboy#41]
Not sure if related to previous issues and just needs a restart or not. Been having issues for a few days now and someone else commented on the Chrome extension page so I thought I'd leave a message here. 

Currently no bet information is populated, which prevents the bot from betting. 

Thanks for the work that you put into the project, it's really cool to see all these data sets come together in a neat project like this.

**Comment by FranciscoAT** [comment]
Thanks the heads up! I'll kick the server in a few :)

**Comment by FranciscoAT** [comment]
Bot looks alive now :) feel free to re-open if things are still not working.
