### ISSUE TITLE
1.5.0 Release Issues (Report Server Issues Here)

### ISSUE THREAD

**Issue by how2vim** [FranciscoAT/saltyboy#46]
Released 1.5.0, should hopefully resolve server downtime issues. Please bug me on this ticket if you're experiencing issues. https://github.com/FranciscoAT/saltyboy/releases/tag/1.5.0

**Comment by hiroweeb** [comment]
Been down for more than an hour, stuck on an exhibition match.

**Comment by FranciscoAT** [comment]
> Been down for more than an hour, stuck on an exhibition match.

Issue reported here: https://github.com/FranciscoAT/saltyboy/issues/64
