### ISSUE TITLE
Feature Request: Expanded debug information

### ISSUE THREAD

**Issue by UnBayleefable** [FranciscoAT/saltyboy#47]
Is it possible for the debug info section to echo the currently set betting parameters (e.g. betting type, max bet etc) so i can confirm if its currently using my updated settings or if its still using the previous ones.

also what about settings for the default bet for exhibs instead of $1?

**Comment by FranciscoAT** [comment]
> Is it possible for the debug info section to echo the currently set betting parameters (e.g. betting type, max bet etc) so i can confirm if its currently using my updated settings or if its still using the previous ones.

Not a bad idea, I think it should be fairly easy to do. I've been wanting to update some UI stuff in the extension anyway. 

> also what about settings for the default bet for exhibs instead of $1?

How would you imagine something like this working?

**Comment by UnBayleefable** [comment]
well id assume you have a check for if its currently an exhibition match and if so bet $1 on red, i would add a text box for changing the  $1 to a custom amount (still bets on red, just doesnt lump you in with all the other bots betting $1)

**Comment by FranciscoAT** [comment]
@UnBayleefable Published the new version. Should propagate down to you once Google approves the new update.

**Comment by UnBayleefable** [comment]
what is the approval timeframe for extensions? ive only got experience with publishing to the play store and usually thats around half an hour.

**Comment by FranciscoAT** [comment]
24hrs+ could be longer. This extension needs certain permissions that require additional scrutiny from Google as well, so that could extend the approval period. Should be here in the next few days hopefully :)
