### ISSUE TITLE
Betting $1 in tournaments when all in is active.

### ISSUE THREAD

**Issue by UnBayleefable** [FranciscoAT/saltyboy#52]
just noticed this today.
![image](https://user-images.githubusercontent.com/20810019/233889692-6a3aa79a-0b67-42a9-b176-1169a5f7d0b8.png)
![image](https://user-images.githubusercontent.com/20810019/233889712-daf594ef-fdab-4842-a3b4-c0910790bb17.png)

**Comment by FranciscoAT** [comment]
This is due to https://github.com/FranciscoAT/saltyboy/issues/51#issuecomment-1519305537. It's a fail safe mechanism. Going to close and leave the other issue open. ETA on fix will hopefully be in a few days. But will have to wait for Waif4u to come back online :(

**Comment by UnBayleefable** [comment]
no worries, didnt know that waifuBot was down.
