### ISSUE TITLE
Tooltip is missing

### ISSUE THREAD

**Issue by SirJazz** [FranciscoAT/saltyboy#53]
The tooltip for the batting strategy seems to be missing:

![image](https://user-images.githubusercontent.com/65920663/235351825-61c4fc8b-0f27-49c2-8e1d-e80f67df9a76.png)

**Comment by FranciscoAT** [comment]
If you click open the `Selected Bet Mode +` header right below the `Betting Mode` entry it should tell you the description:

![image](https://user-images.githubusercontent.com/5719634/235357406-c4d62d41-dd2f-4037-ad30-8789001a2c1d.png)

**Comment by SirJazz** [comment]
i guess i am blind!
