### ISSUE TITLE
Add confidence rating limiter to extension UI

### ISSUE THREAD

**Issue by Manthaknee** [FranciscoAT/saltyboy#57]
add a bet setting to extension that limits bets based on user selected confidence rating percentage. i.e. if Salty Boy confidence rating is above 80% bet, no betting unless confidence rating met. Similar to "all in until" but could be titled "limit bets to confidence rating above"

**Comment by FranciscoAT** [comment]
Sounds reasonable. I would imagine if this feature is enabled that we'd still want the bot to bet $1 minimum regardless.

**Comment by Manthaknee** [comment]
A minimum bet of 1 could work. The chrome extension could include new check box titled "confidence mode" and a new field that let the user set the confidence percentage between 50-99 (I assume the bot designates confidence between these values). I have found that while the bot does win at a decent rate, limiting when it can bet would help in the four betting modes and upset mode.  Another solution is to create a single confidence mode field that can be set between 50-99 and doesn't override upset mode, so that if the confidence of the favorite is above a certain value the bot will revert to a 0 bet or a 1 bet.

**Comment by Manthaknee** [comment]
One further thought is I am not sure how naive mode works so not sure how it would interact with a new confidence mode.

**Comment by FranciscoAT** [comment]
Implementation I coded up is just a permanently active setting where you can submit a number between [50, 100) and if the confidence is less than the given number it will bet $1. Setting it to 50 is effectively the same as disabling the setting.

**Comment by FranciscoAT** [comment]
1.7.0 submitted for review on the Chrome Store. Should be out in the next few days.

**Comment by Manthaknee** [comment]
Can't wait to try it out! Can you explain here the difference between the betting modes? Or should I open a new issue? I can open one asking for the readme to include a betting mode explainer. I.e. naive, passive, rng, etc. Saw the explanation on the salty-boy domain for elo and tiered but inclusion in the github readme.md in the extension section would be a helpful explainer.

**Comment by FranciscoAT** [comment]
https://github.com/FranciscoAT/saltyboy/tree/master/extension/src/content_scripts/bet_modes you can view the betting algorithms here. They also should all feature a doc string with a more in-depth explanation of how they operate.
