### ISSUE TITLE
add a win rate option

### ISSUE THREAD

**Issue by yunghiro** [FranciscoAT/saltyboy#59]
it would be nice to have a win rate option

**Comment by FranciscoAT** [comment]
How would you propose it function?

**Comment by yunghiro** [comment]
Sorry for the late response, It would function by seeing which fighter has the higher win rate between the two. Then, it would pick the fighter with the higher win rate.

**Comment by FranciscoAT** [comment]
Hey there hasn't really been any input on this feature request. So I'm going to close, if you have any further thoughts on this feel free to re-open with a comment! :)
