### ISSUE TITLE
Remove Upset Bet Algorithm

### ISSUE THREAD

**Issue by nixpayn** [FranciscoAT/saltyboy#63]
It doesnt seem to matter what setting i pick, it seems to bet blue like.. 95% of the time.

**Comment by FranciscoAT** [comment]
Feels surprising, although I've never done a deep dive on the stats for each betting algorithm. What are your current configurations?

**Comment by nixpayn** [comment]
I cant seem to copy the text, cant even right click in the popup. Stupid chrome. Lets see if this works. 

I usually turn off upset betting for tourneys and i noticed that on several fights the app was like in 75-90% sure red is gonna win, and it bet blue anyway.

![image](https://github.com/FranciscoAT/saltyboy/assets/38497537/f473172f-28da-4786-88f2-bf32685be362)

**Comment by nixpayn** [comment]
Thanks!

**Comment by FranciscoAT** [comment]
Hey so I had it running for a bit using the same betting algorithm (ELO) and Confidence Threshold it seemed to be operating correctly. Betting on Blue or Red based on the ELO calculation. 

If you want to try and maybe debug and see if there's any insights on your end I would suggest Enabling Debug mode in the "Debug Settings" in the popup. You can hover over the tooltip to the right on how to view the debug messages. Maybe there's something in there that might  jump out as contrary.

**Comment by FranciscoAT** [comment]
Hey! Just going to close this issue out, do let me know if in your debugging adventures you find something contrary to the way the bot is behaving vs the way it should be behaving. Also if we're dealing with a small sample set even if it bet blue almost 100% of the time with the algorithm if you expand that sample set to a much larger set it's probably close to a 50/50 on red vs blue, provided the way SaltyBet allocates the fighters positions is totally random. :)

**Comment by nixpayn** [comment]
I looked through my betting history, its actually betting 100% blue

![image](https://github.com/FranciscoAT/saltyboy/assets/38497537/895896ee-f0f2-4209-b4e3-11418c84b5b0)

**Comment by FranciscoAT** [comment]
hmm something does feel off, definitely not representative. Can you try the "Alert Local Storage" thing again? I know you can't select but apparently you should just be able to hit CTRL+C when the alert pops up and it should put everything in the alert in your clipboard.

eg.:

```
{  "appSettings": {    "enableOverlay": true  },  "betSettings": {    "allInTournaments": true,    "allInUntil": "0",    "betMode": "elo",    "betTier": {      "a": true,      "b": true,      "p": true,      "s": true,      "x": true    },    "confidenceThreshold": "55",    "enableBetting": true,    "exhibitionBet": "1",    "maxBetAmount": "0",    "maxBetPercentage": "5",    "upsetMode": false  },  "debugSettings": {    "debugEnabled": true  },  "matchStatus": {    "betConfirmed": true,    "currentStatus": "betting",    "loggedIn": true  },  "winnings": {    "session": 828852,    "total": -8637130  }}
```

**Comment by nixpayn** [comment]
{  "appSettings": {    "enableOverlay": true  },  "betSettings": {    "allInTournaments": true,    "allInUntil": "0",    "betMode": "upset",    "betTier": {      "a": true,      "b": true,      "p": true,      "s": true,      "x": true    },    "confidenceThreshold": "65",    "enableBetting": true,    "exhibitionBet": "1",    "maxBetAmount": "250000",    "maxBetPercentage": "3",    "upsetMode": true  },  "debugSettings": {    "debugEnabled": true  },  "matchStatus": {    "betConfirmed": true,    "currentStatus": "betting",    "loggedIn": true  },  "winnings": {    "session": 124801913,    "total": 147700160  }}

**Comment by nixpayn** [comment]
On a side note, just betting all blue got me up to about 32m lol, but down to 22 since saturday :P

**Comment by FranciscoAT** [comment]
oh lol I see the issue. I would advise against using "Upset Bet Mode".

https://github.com/FranciscoAT/saltyboy/blob/master/extension/src/content_scripts/bet_modes/upset.js

Re-reading the betting logic that no matter what it will always bet on Red.
I notice that you also have the `upsetMode: true` flag set. Which means
this will invert who it will bet on for every single bet. Meaning that
"upset" will vote red 100% of the time, then with the upset mode flag it
will flip it to vote blue 100% of the time.

I would advise switching to "Naive" betting mode and keeping the "Upset
Mode" flag enabled. This will have the same intended effect as the "Upset"
bet mode. I'll be honest with the new flag, I don't think we need the
"Upset" bet algorithm anymore. Under the hood back before I had this flag
both "Naive" and "Upset" are the same algorithm but with the intent they
invert who to bet on.

**Comment by FranciscoAT** [comment]
Re-opening issue to remove the "Upset" bet algorithm.

**Comment by nixpayn** [comment]
That helped, trending upwards again, back to 30m :) Thanks!
