### ISSUE TITLE
Scraping has failed

### ISSUE THREAD

**Issue by BigIsBig453** [FranciscoAT/saltyboy#64]
As of this post, the scraping on SaltyBet has been nonfunctional for at least 20 matches.
Navigating to [Current Match](https://salty-boy.com/current-match) returns the following at all times
 `{"fighter_blue":"Team B","fighter_blue_info":null,"fighter_red":"Team A","fighter_red_info":null,"match_format":"exhibition","tier":null}`

Obviously, this isn't right. I'm not sure how you are to fix it, but please try to do so.

**Comment by FranciscoAT** [comment]
Thanks for the heads up. Scraper is back up and running. Feel free to re-open if you encounter more issues.
