### ISSUE TITLE
only bets 1

### ISSUE THREAD

**Issue by bigxdangerous** [FranciscoAT/saltyboy#65]
not sure how too use the newer salty bet bot i useto use the old one alot, just curious is it perma banned now or does it occasionally work?

**Comment by FranciscoAT** [comment]
Not banned every once in a while the bot that scrapes the Twitch chat for matches gets disconnected from the IRC. Usually a matter of me do the time old classic:

![have_you_tried_turning_it_off_and_on_again-1709260140](https://github.com/FranciscoAT/saltyboy/assets/5719634/95ef90e5-fa97-4f06-b044-d95a06854e92)

Anyway did the above, it should be happy now. Feel free to open a new issue if this happens again or to re-open this one. Enjoy the salt mines!
