### ISSUE TITLE
Update Extension to separate logic of Enable / Disable Extension & Enable / Disable Betting

### ISSUE THREAD

**Issue by hiroweeb** [FranciscoAT/saltyboy#66]
I was wondering, if the extension can read how much salty bucks you have (even tho it seems buggy), could it try to read for saltybet's gold stats shown on the betting list before a fight?

I had a few ideas : 
- Every time the bot (saltyboy) detects a new betting phase is open, it could try to scan the saltybet gold stats a few times locally, and fallback to the bot's stats if it doesn't detect it.
- Offer saltybet gold to the bot and make it use the official stats to determine confidence. (don't know if it's possible at all, I'm not that knowledgeable about python)

All assuming the elo and tiered elo are calculated based on the number of matches, winrate and tiern but correct me if I'm wrong.

**Comment by FranciscoAT** [comment]
Hey!

Not sure on this one? I don't have Illuminati on SaltyBet. Also not sure if they provide a robust API for this kind of stuff, might need more information. Additionally, I think if I were to implement something like this I'd probably have the extension itself query SaltyBet Gold (if possible)'s dataset requiring the user to have Illuminati. I feel that circumventing this and just straight up allowing anyone access to the data by proxy of the bot feels like a step too far.

> I was wondering, if the extension can read how much salty bucks you have (even tho it seems buggy), could it try to read for saltybet's gold stats shown on the betting list before a fight?

I agree though here for sure, the initial roll-out of the feature was something I coded up on a whim while making a bunch of updates to the bot one day. There is definitely more robust and better ways to handle this process.

Currently, I am re-writing the back-end in Rust as well as make several technology upgrades. I think I'll probably be doing the same with the extension, more than likely moving it to TypeScript from vanilla JS. 

> All assuming the elo and tiered elo are calculated based on the number of matches, winrate and tiern but correct me if I'm wrong.

From an excerpt on the website https://salty-boy.com/:

> ELO is calculated by the bot that watches the matches. The "elo" value is the fighters total ELO and is compared to other fighters ELO. ELO for a fighter begins at 1500 and uses a K Value of 32. Where as "tier_elo" is the exact same as the fighter's ELO value. However, when a fighter changes tier their "tier_elo" will reset to 1500. Otherwise, the calculations are the same as before. Generally, a fighters ELO and Tier ELO will be equivalent if they have never left their current tier.

You can read more about ELO here: https://metinmediamath.wordpress.com/2013/11/27/how-to-calculate-the-elo-rating-including-example/.

Additionally the algorithm for SaltyBoy can be found here: https://github.com/FranciscoAT/saltyboy/blob/master/bot/src/database.py#L268

The `elo` and `tier_elo` values get updated each time a fighter has a new match.

**Comment by hiroweeb** [comment]
> Not sure on this one? I don't have Illuminati on SaltyBet. Also not sure if they provide a robust API for this kind of stuff, might need more information.

I'd be down to gift a month to whichever account you're using so you can check it out.

> I feel that circumventing this and just straight up allowing anyone access to the data by proxy of the bot feels like a step too far.

After thinking about it again, it does sound like Salty gold itself. 

> Generally, a fighters ELO and Tier ELO will be equivalent if they have never left their current tier.

From what I saw, the only real match history you have is the one you bet on. So tier elo could not be as reliable as it is with your current bot.
And thanks for the documentation about elo calculation !

I also just got another suggestion, which is to enable confidence whenever overlay is active without having to turn on auto bet. I tried fiddling with code but didn't manage to do much. Should I make another issue for that?

**Comment by FranciscoAT** [comment]
> I'd be down to gift a month to whichever account you're using so you can check it out.

Thank you for the offer! Although I'm sure I can always give SaltyBet some $ to take a look around. I don't think I'll be able to invest time into looking into this right now howeer. I'm in the process of migrating the back-end from Python to Rust, as a learning experience, and moving the database off of SQLite to PostgreSQL. 

This may also involve me moving the extension code off of Vanilla JS to TS also might involve some new endpoint usages etc...

> I also just got another suggestion, which is to enable confidence whenever overlay is active without having to turn on auto bet. I tried fiddling with code but didn't manage to do much. Should I make another issue for that?

This is actually a great idea, if you don't mind I'll transition this issue title into this actually! I think originally I had built the "Enable Betting" button as an on/off switch which isn't really reflective of it doing what we want it to do. But rather we should have an "Enable Betting" and "Enable / Disable Extension" buttons.

**Comment by hiroweeb** [comment]
> I don't think I'll be able to invest time into looking into this right now howeer. I'm in the process of migrating the back-end from Python to Rust, as a learning experience, and moving the database off of SQLite to PostgreSQL.

Take all the time you need, it was merely a suggestion after all !
It's already great enough that you took on your own time to code all of this and still maintain it to this day.

> This is actually a great idea, if you don't mind I'll transition this issue title into this actually!

Sure go ahead.
