### ISSUE TITLE
unable to run web portion

### ISSUE THREAD

**Issue by myntfarm** [FranciscoAT/saltyboy#67]
Hello! trying to run your project on my own machine but am hitting a hard stop when running the web portion following your instructions.

Traceback (most recent call last):
  File "/home/mynt/saltyboy/web/main.py", line 12, in <module>
    from flasgger import Swagger
  File "/home/mynt/saltyboy/web/.venv/lib/python3.10/site-packages/flasgger/__init__.py", line 10, in <module>
    from .base import Swagger, Flasgger, NO_SANITIZER, BR_SANITIZER, MK_SANITIZER, LazyJSONEncoder  # noqa
  File "/home/mynt/saltyboy/web/.venv/lib/python3.10/site-packages/flasgger/base.py", line 28, in <module>
    from flask.json import JSONEncoder
ImportError: cannot import name 'JSONEncoder' from 'flask.json' (/home/mynt/saltyboy/web/.venv/lib/python3.10/site-packages/flask/json/__init__.py)

my reseach puts me to https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0

*json_encoder and json_decoder attributes on app and blueprint, and the corresponding json.JSONEncoder and JSONDecoder classes, are removed.*

not sure if you want to downgrade your flask version or if a change is in the works.

**Comment by myntfarm** [comment]
just wanted to confirm that i manually rolled flask back to 2.2.3 as referenced was the previous working version and that supports the function. And now i am able to run the web portion.

**Comment by FranciscoAT** [comment]
Good catch, I think I might've ran a random `poetry lock` at some point resulting in the Flask version being upgraded. 

I may just leave this issue open without fixing it for now as I'm actually in the process of doing a major overhaul of the back-end. This involves moving from Python to Rust and migrating off of SQLite to PostgreSQL. No timeline on this yet. That being said if you were spinning this up locally to write some new features with the intention to merge it back in to this Repository do let me know what your ideas were and I'll be sure to consider them and see if I can't fit them into the new Rust re-write! :)

**Comment by myntfarm** [comment]
no worries that all makes sense. I was just curious to spin things up and see how it all works. saw your comment about not abusing the API so thought it would be better to just pin up my own node to poke around.

Curious. since i have no data on fighters my "fighter_info" is null so the bot has no confidence. Is this just something i need to collect data on? would you be willing to share a copy of your current db?

**Comment by FranciscoAT** [comment]
Yea that warning is mainly there to ask people not to constantly hit the
API on an infinite loop or something like that. The server is running on a
$5 Vultr instance so not the most beefy machine lol.

And yea no problem feel free to scrape the API or I can post the database
later tonight.

**Comment by myntfarm** [comment]
Thanks i'd really appreciate it if you could post that. in the mean time ill just be playing around with my own nodes and let you know if i see anything interesting. Beyond just making sure the code recovers when it freezes.

**Comment by FranciscoAT** [comment]
[saltyboy.db.tar.gz](https://github.com/FranciscoAT/saltyboy/files/12340660/saltyboy.db.tar.gz)

Yesterday's db dump :)

**Comment by FranciscoAT** [comment]
Hiya a year and a half later! I decided to give this project some TLC. You should be able to run things fine now ;)
