### ISSUE TITLE
Team Betting

### ISSUE THREAD

**Issue by Bd134** [FranciscoAT/saltyboy#68]
Is there a way to disable betting on 2v2/2v1 matches? My bets currently max and fights seem stacked. 

Love the bot works great! Thank you!

**Comment by FranciscoAT** [comment]
Not sure what you mean by 2v2 and 2v1 matches? Do you mean the Exhibition
matches?

And glad you enjoy the bot!

**Comment by Bd134** [comment]
Yes exhibition, it seems like alot of 2v1 matches in particular the bot bets max on the team of 2 and gets blown out. Reliability of 2v2 as well so I wasn't sure if there is or would suggest a way to exclude any team matches.

Maybe my settings are wacky. 

Thanks!

**Comment by FranciscoAT** [comment]
What do you have set for "Exhibition Bet"?

**Comment by Bd134** [comment]
15k

**Comment by Bd134** [comment]
1v1 exhibition works great! Just those pesky 2v1 2v2

**Comment by FranciscoAT** [comment]
Ah okay that makes sense. Okay so I would advise against using the bot to try and vote on Exhibitions. The upstream service has no understanding of exhibition matches / their line ups / who is involved etc... Most of the betting algorithms just bet blindly and the bot compensates by trying it's best to limit how it bets on the Exhibition matches by having "Exhibition Bet" slider.

**Comment by Bd134** [comment]
Okay great! Thanks!

**Comment by FranciscoAT** [comment]
Yea if you know a good way on how to better extract data from Exhibition matches I'm all ears but would definitely avoid putting any number in that slider that you don't want to lose! 😅
