### ISSUE TITLE
chrome extension not betting?

### ISSUE THREAD

**Issue by marskiontop** [FranciscoAT/saltyboy#73]
have all areas filled out, but it hasnt made a single bet yet. 

got chrome extension enabled and running it currently but thats about it, is there a step im missing?

**Comment by FranciscoAT** [comment]
https://salty-boy.com/last-match looks like the bot is up to date. Are you logged in? Can you post your configuration?

1. Click on SaltyBoy extension pop-up.
2. Scroll down to "Debug Information" and open up the section by clicking on the "+".
3. Click on "Alert & Log Local Storage", this should show a pop-up.
4. Hit CTRL+C, you shouldn't need to select to copy this.
5. Paste your configuration in a comment in code blocks like so:

````
```
<ctrl+v>
```
````

```
{  "appSettings": {    "enableOverlay": true  },  "betSettings": {    "allInTournaments": true,    "allInUntil": "0",    "betMode": "elo",    "betTier": {      "a": true,      "b": true,      "p": true,      "s": true,      "x": true    },    "confidenceThreshold": "55",    "enableBetting": true,    "exhibitionBet": "1",    "maxBetAmount": "0",    "maxBetPercentage": "5",    "upsetMode": false  },  "debugSettings": {    "debugEnabled": true  },  "matchStatus": {    "betConfirmed": true,    "currentStatus": "betting",    "loggedIn": true  },  "winnings": {    "session": 828852,    "total": -8637130  }}
```

**Comment by marskiontop** [comment]
{  "appSettings": {    "enableOverlay": true  },  "betSettings": {    "allInTournaments": true,    "allInUntil": "0",    "betMode": "upset",    "betTier": {      "a": true,      "b": true,      "p": true,      "s": true,      "x": true    },    "confidenceThreshold": "50",    "enableBetting": true,    "exhibitionBet": "350",    "maxBetAmount": "350",    "maxBetPercentage": "0",    "upsetMode": false  },  "winnings": {    "session": 0,    "total": 0  }}

**Comment by marskiontop** [comment]
im logged in and everything

**Comment by FranciscoAT** [comment]
Oh wow that really is peculiar. Your settings look fine. Pretty standard stuff. Let's go a level deeper here. Like before pop open the extension then go open up "Debug Information". Tick the box that says "Enable Debugging Mode". Then hover over the "?" next to it. It should explain to you how to get the console open. The extension should attempt to log everything it is doing. If something is failing hopefully we should see it there. 

Let it run for a bit and let me know if there happen to be any stack traces or other things that get created in the console.

**Comment by marskiontop** [comment]
ok got the console open for salty bet, full transparency not to sure what im suppose to be looking for

there is a few things stack ed that say Failed to load resource: net::ERR_BLOCKED_BY_CLIENT


also
 DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT

these are the main 2 i see repeating

**Comment by marskiontop** [comment]
https://sb.scorecardresearch.com/p?c1=2&c2=6745306&ns_type=hidden&ns_st_sv=5.1.3.160420&ns_st_smv=5.1&ns_st_it=r&ns_st_id=1694975980221&ns_st_ec=33&ns_st_sp=1&ns_st_sc=1&ns_st_sq=16&ns_st_ppc=1&ns_st_apc=1&ns_st_spc=1&ns_st_cn=1&ns_st_ev=hb&ns_st_po=4740022&ns_st_cl=0&ns_st_hc=83&ns_st_mp=js_api&ns_st_mv=5.1.3.160420&ns_st_pn=1&ns_st_tp=0&ns_st_ci=41114333160&ns_st_pt=4740022&ns_st_dpt=1011434&ns_st_ipt=60001&ns_st_et=7172036&ns_st_det=1011434&ns_st_upc=4740022&ns_st_dupc=1011434&ns_st_iupc=60001&ns_st_upa=4740022&ns_st_dupa=1011434&ns_st_iupa=60001&ns_st_lpc=4740022&ns_st_dlpc=1011434&ns_st_lpa=4740022&ns_st_dlpa=1011434&ns_st_pa=4740022&ns_ts=1694983153218&ns_st_bc=0&ns_st_dbc=0&ns_st_bt=0&ns_st_dbt=0&ns_st_bp=0&ns_st_skc=0&ns_st_dskc=0&ns_st_ska=0&ns_st_dska=0&ns_st_skd=0&ns_st_skt=0&ns_st_dskt=0&ns_st_pc=15&ns_st_dpc=0&ns_st_pp=15&ns_st_br=0&ns_st_ub=0&ns_st_ki=1200000&ns_st_pr=*null&ns_st_sn=*null&ns_st_en=*null&ns_st_ep=%F0%9F%A7%82%20Salty%20Bet%20Dream%20Cast%20Casino!%20%F0%9F%92%B0%20Place%20your%20bets%20at%20www.saltybet.com!%20%F0%9F%A7%82%2024%2F7%20MUGEN%20%F0%9F%A7%82&ns_st_ct=vc&ns_st_ge=Gaming&ns_st_st=SaltyBet&ns_st_ce=1&ns_st_ia=0&ns_st_ddt=2023-09-15&ns_st_tdt=*null&ns_st_pu=*null&ns_st_ti=*null&c3=TWITCH&c4=twitch.tv&c6=*null&c7=https%3A%2F%2Fplayer.twitch.tv%2F%3Fchannel%3Dsaltybet%26parent%3Dwww.saltybet.com&c8=Twitch&c9=https%3A%2F%2Fwww.saltybet.com%2F&cs_ucfr=*null net::ERR_BLOCKED_BY_CLIENT
 
this also keep popping up virtually every 10 seconds or so when a fight loads

**Comment by FranciscoAT** [comment]
i think that's something else. Here you can follow along in the below video. There's a bit of a lull in the middle but you can skip to the end to see what the debug logging looks like. Let me know in this logging view if you run into any issues. The extension appears to still be happy for myself on my end. 


https://github.com/FranciscoAT/saltyboy/assets/5719634/b9f7fde7-c687-4368-9782-3f3e0a93b7d3

**Comment by marskiontop** [comment]
so noting is popping up that int he window just a blank screen, i ran it for the last 2 match of tournament, and currently in exhibition matches where it should be betting 350

**Comment by FranciscoAT** [comment]
Would you mind giving things the good old on / off? Remove extension + close Chrome + reopen + reinstall the extension?

**Comment by marskiontop** [comment]
sorry for the delay response, fix was incredibly simple lol, cleared cache and cookies and everything works
