### ISSUE TITLE
Bot down

### ISSUE THREAD

**Issue by hiroweeb** [FranciscoAT/saltyboy#74]
Bot seems to have been down for more than a day, just a heads up if you have spare time to kick it. Thanks!

**Comment by nixpayn** [comment]
came here for the same :D

**Comment by Stuemke17** [comment]
I believe it needs a kick, please and thank you! <3

**Comment by hiroweeb** [comment]
Hi! The bot seems to be down, if you have a minute to kick it that'd be awesome! Thanks ❤️

**Comment by hiroweeb** [comment]
Hi, quick bump! thanks in advance ❤️
