### ISSUE TITLE
bot stuck again

### ISSUE THREAD

**Issue by OreoFire** [FranciscoAT/saltyboy#92]
It's stuck on an exhib match and hasn't changed since then

**Comment by FranciscoAT** [comment]
Thanks! Gave it a kick. Working on an alternative solution right now
actually. Fingers crossed it'll try and solve this issue. Only hopefully
resulting in minor downtimes of upto ~10-15 minutes worst case.

**Comment by FranciscoAT** [comment]
Deployed https://github.com/FranciscoAT/saltyboy/pull/93 to production. Going to leave this open to see if the watchdog can't detect if the socket got disconnect by remote (Twitch). Now we play the waiting game.

![Lenny Waiting](https://c.tenor.com/W09LnKMX3qQAAAAC/tenor.gif)

**Comment by FranciscoAT** [comment]
Looks like things are looking good. Did see a point where the watchdog auto-restarted the bot after detecting it was stuck. I rejigged the code again to try and provide much much less downtime and improved logging fixes.

Now we wait again. Hopefully, once this is done you'll never need to ask me to kick the bot again. :sweat_smile:

**Comment by FranciscoAT** [comment]
See: https://github.com/FranciscoAT/saltyboy/issues/62#issuecomment-1977312706. Closing :)
